# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
orbs:
  python: circleci/python@2.1.1
  workflows:
    example-workflow:
      jobs:
        - python/test:
            setup:  /my-app |-- node_modules/ |-- public/     |-- index.html     |-- favicon.ico |-- src/     |-- components/         |-- Tarot/             |-- TarotCardGenerator.js         |-- Astrology/             |-- BirthChartGenerator.js         |-- HumanDesign/             |-- HumanDesignChartGenerator.js         |-- Numerology/             |-- NumerologyChartGenerator.js         |-- Journal/             |-- DailyAffirmations.js             |-- ReflectionSpace.js         |-- Auras/             |-- AurasExplanation.js         |-- Starseeds/             |-- StarseedsGenerator.js         |-- DoloresCannon/             |-- DoloresCannonBooks.js     |-- App.js     |-- index.js |-- package.json |-- webpack.config.js |-- .babelrc 
            
            orbs:
  jq: circleci/jq@3.0.0
  orbs:
  node: circleci/node@5.1.0
  